version: '3'

services:

  mongo-db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - exchange-backend

  exchange-core:
    container_name: "exchange-core"
    build: .
    # command: python main.py && tail -f /dev/null
    env_file:
        - .env
    ports:
      - '8000:8000'
    volumes:
      - ./src:/usr/app/src
    networks:
      - exchange-backend

networks:
  exchange-backend:
    name: exchange-backend
    driver: bridge