version: '3'

services:

  exchage-core:
    container_name: "exchage-core"
    build: .
    command: python main.py && tail -f /dev/null
    env_file:
        - .env
    ports:
      - '8000:8000'
    volumes:
      - ./src:/usr/app/src
